kepler:
  logs:
    buffer_size: 0

services:
  unhealthy-service:
    command: ["sh", "-c", "echo Starting; sleep 300"]
    healthcheck:
      test: ["sh", "-c", "exit 1"]
      interval: 1s
      timeout: 5s
      retries: 2
      start_period: 0s
