kepler:
  logs:
    buffer_size: 0

services:
  on-unhealthy-service:
    command: ["sh", "-c", "echo ON_UNHEALTHY_START; sleep 300"]
    restart: "on-failure|on-unhealthy"
    healthcheck:
      run: "exit 1"
      interval: 1s
      timeout: 5s
      retries: 2
      start_period: 0s
