kepler:
  logs:
    buffer_size: 0

services:
  healthy-service:
    command: ["sh", "-c", "echo Starting; sleep 300"]
    healthcheck:
      run: "exit 0"
      interval: 2s
      timeout: 5s
      retries: 2
      start_period: 0s
