kepler:
  logs:
    buffer_size: 0

services:
  hook-unhealthy-service:
    command: ["sh", "-c", "echo HOOK_UNHEALTHY_START; sleep 300"]
    restart: "on-unhealthy"
    healthcheck:
      run: "exit 1"
      interval: 1s
      timeout: 5s
      retries: 2
      start_period: 0s
    hooks:
      post_healthcheck_fail:
        - run: "echo POST_HEALTHCHECK_FAIL_HOOK"
