kepler:
  logs:
    buffer_size: 0

services:
  glob-watch-service:
    command: ["sh", "-c", "echo GLOB_WATCH_START; sleep 300"]
    working_dir: __WATCH_DIR__
    restart:
      policy: always
      watch:
        - "**/*.txt"
