kepler:
  logs:
    buffer_size: 0

services:
  lua-context-service:
    command: !lua |
      -- The 'service.name' variable contains the service name
      local svc_name = service.name or "unknown"
      return {"sh", "-c", "echo SERVICE_NAME=" .. svc_name .. "; sleep 300"}
