[workspace]
members = [
    "kepler-cli",
    "kepler-protocol",
    "kepler-daemon",
    "kepler-exec",
    "kepler-tests",
    "kepler-e2e",
]
resolver = "2"

[workspace.package]
version = "0.2.0"

[profile.release]
strip = true
