services:
  hook-wd-service:
    env_file: __ENV_FILE__
    command: ["sh", "-c", "echo HOOK_WD_SERVICE_RUNNING && sleep 30"]
    hooks:
      on_start:
        working_dir: ${HOOK_DIR}
        run: "pwd >> __MARKER_FILE__"
    restart: no
