kepler:
  logs:
    buffer_size: 0

services:
  never-ready:
    command: ["sh", "-c", "echo Starting; sleep 300"]
    healthcheck:
      run: "exit 1"
      interval: 1s
      retries: 999

  slow-service:
    command: ["sh", "-c", "echo Starting; sleep 300"]
    depends_on:
      never-ready:
        condition: service_healthy
