services:
  timeout-service:
    command: ["sh", "-c", "echo Starting; sleep 300"]
    healthcheck:
      # Sleep longer than timeout to trigger timeout
      test: ["sh", "-c", "sleep 10"]
      interval: 2s
      timeout: 1s
      retries: 2
      start_period: 0s
