services:
  start-period-service:
    command: ["sh", "-c", "echo Starting; sleep 300"]
    healthcheck:
      test: ["CMD-SHELL", "exit 1"]
      interval: 1s
      timeout: 5s
      retries: 2
      start_period: 5s
