kepler:
  logs:
    buffer_size: 0  # Disable buffering for immediate writes

services:
  filter-service-a:
    command: ["sh", "-c", "echo FILTER_A_MESSAGE; sleep 300"]
  filter-service-b:
    command: ["sh", "-c", "echo FILTER_B_MESSAGE; sleep 300"]
