kepler:
  logs:
    buffer_size: 0

services:
  svc-stop-hook-service:
    command: ["sh", "-c", "echo Starting; sleep 300"]
    hooks:
      pre_stop:
        run: |
          echo "SERVICE_PRE_STOP_RAN" >> __MARKER_FILE__
