kepler:
  logs:
    buffer_size: 0
  hooks:
    pre_start:
      if: "not service.initialized"
      run: |
        echo "ON_INIT_RAN" >> __MARKER_FILE__

services:
  init-hook-service:
    command: ["sh", "-c", "echo Starting; sleep 300"]
