kepler:
  logs:
    buffer_size: 0

services:
  svc-exit-hook-service:
    command: ["sh", "-c", "echo Starting; sleep 1; exit 0"]
    restart: no
    hooks:
      post_exit:
        run: |
          echo "SERVICE_POST_EXIT_RAN" >> __MARKER_FILE__
