kepler:
  logs:
    buffer_size: 0
  hooks:
    pre_init:
      run: |
        echo "PRE_INIT_RAN" >> __MARKER_FILE__

services:
  init-hook-service:
    command: ["sh", "-c", "echo Starting; sleep 300"]
