kepler:
  logs:
    buffer_size: 0
  hooks:
    on_cleanup:
      run: |
        echo "ON_CLEANUP_RAN" >> __MARKER_FILE__

services:
  cleanup-hook-service:
    command: ["sh", "-c", "echo Starting; sleep 300"]
