kepler:
  logs:
    buffer_size: 0

services:
  svc-start-hook-service:
    command: ["sh", "-c", "echo Starting; sleep 300"]
    hooks:
      pre_start:
        run: |
          echo "SERVICE_PRE_START_RAN" >> __MARKER_FILE__
