kepler:
  logs:
    buffer_size: 0
  hooks:
    pre_stop:
      run: |
        echo "PRE_STOP_RAN" >> __MARKER_FILE__

services:
  stop-hook-service:
    command: ["sh", "-c", "echo Starting; sleep 300"]
