kepler:
  logs:
    buffer_size: 0
  hooks:
    pre_start:
      run: |
        echo "PRE_START_RAN" >> __MARKER_FILE__

services:
  start-hook-service:
    command: ["sh", "-c", "echo Starting; sleep 300"]
