services:
  healthcheck-hooks-service:
    command: ["sh", "-c", "echo Starting; sleep 300"]
    healthcheck:
      test: ["sh", "-c", "exit 0"]
      interval: 2s
      timeout: 5s
      retries: 2
      start_period: 0s
    hooks:
      on_healthcheck_success:
        run: |
          echo "HEALTHCHECK_SUCCESS_HOOK" >> __MARKER_FILE__
      on_healthcheck_fail:
        run: |
          echo "HEALTHCHECK_FAIL_HOOK" >> __MARKER_FILE__
