kepler:
  logs:
    buffer_size: 0

services:
  dep-source:
    depends_on:
      - dep-target
    command: ["sh", "-c", "echo DEP_SOURCE_START && sleep 30"]
    restart: no

  dep-target:
    command: ["sh", "-c", "echo DEP_TARGET_START && sleep 30"]
    restart: no
