kepler:
  logs:
    buffer_size: 0

services:
  default-service:
    env_file: __ENV_FILE__
    environment:
      - DEFAULT_VAL=${{ env.UNDEFINED_VAR or "default_value_used" }}$
    command: ["sh", "-c", "echo $DEFAULT_VAL && sleep 30"]
    restart: no
