kepler:
  logs:
    buffer_size: 0

services:
  health-service:
    env_file: __ENV_FILE__
    command: ["sh", "-c", "echo HEALTH_SERVICE_RUNNING && sleep 30"]
    healthcheck:
      run: "test \"$HEALTH_CHECK_VALUE\" = \"healthy\""
      interval: 1s
      retries: 3
    restart: no
