kepler:
  logs:
    buffer_size: 0

services:
  limits-service:
    env_file: __ENV_FILE__
    command: ["sh", "-c", "echo LIMITS_SERVICE_RUNNING && sleep 30"]
    limits:
      memory: ${{ env.MEM_LIMIT }}
    restart: no
