kepler:
  logs:
    buffer_size: 0

services:
  hook-wd-service:
    env_file: __ENV_FILE__
    command: ["sh", "-c", "echo HOOK_WD_SERVICE_RUNNING && sleep 30"]
    hooks:
      pre_start:
        working_dir: ${{ hook.env.HOOK_DIR }}$
        run: "pwd >> __MARKER_FILE__"
    restart: no
